"""Run configuration.

Configs are YAML files under ``experiments/configs/``. Everything the
orchestration loop, the agents and the evaluation harness need is declared here,
so a run is reproducible from ``(config file, seed, git SHA)`` alone.

Two validators enforce invariants that a careless config edit could otherwise
break silently:

* ``_check_simulator_family`` — the simulated learner's surface model must come
  from a different model family than the diagnostic agent, so the learner is not
  generated by the same lineage that classifies it.
* ``_check_zpd_band`` — the mastery band must be non-degenerate.
"""

from __future__ import annotations

import hashlib
import json
from pathlib import Path
from typing import Literal

import yaml
from pydantic import BaseModel, Field, model_validator

from agent_newton.core.state.schema import Emphasis

Provider = Literal["ollama", "anthropic", "openai"]
Arm = Literal["coupled", "decoupled"]
SurfaceMode = Literal["symbolic", "llm"]

# Each agent has an LLM implementation and at least one model-free counterpart.
# The counterparts are not merely test doubles — they are experimental
# conditions: the `oracle` and `noised_oracle` diagnostics are what the real one
# is compared against to attribute system outcomes to diagnostic error, and the
# model-free set as a whole is what makes fast, exactly reproducible runs
# possible.
TutorImpl = Literal["llm", "template"]
DiagnosticImpl = Literal["llm", "oracle", "noised_oracle"]
#: ``goal_directed`` routes toward the domain's declared goals from the learner
#: model. ``greedy`` is the undirected predecessor — frontier selection with no
#: target — kept as the baseline the directed planner is compared against.
#: ``reverse`` and ``shuffled`` are ordering probes: they cover the same
#: material as ``goal_directed`` but violate the prerequisite order, so a
#: comparison against them measures whether that order matters at all.
PlannerImpl = Literal[
    "llm", "goal_directed", "greedy", "oracle", "reverse", "shuffled"
]


# Model-name prefix -> developer. Used only by the circularity check: what
# matters is that the simulator and the diagnostic do not share a lineage.
_FAMILY_PREFIXES: tuple[tuple[str, str], ...] = (
    ("gemma", "google"),
    ("gemini", "google"),
    ("gpt-oss", "openai"),
    ("gpt-", "openai"),
    ("o1", "openai"),
    ("o3", "openai"),
    ("claude", "anthropic"),
    ("qwen", "alibaba"),
    ("llama", "meta"),
    ("mistral", "mistral"),
    ("mixtral", "mistral"),
    ("phi", "microsoft"),
    ("deepseek", "deepseek"),
)


def model_family(model: str) -> str:
    """Best-effort developer lineage for a model name.

    Unknown models return ``"unknown:<name>"`` rather than a shared bucket, so
    two unrecognised models never compare equal and accidentally trip the
    circularity check into passing.
    """
    name = model.strip().lower()
    for prefix, family in _FAMILY_PREFIXES:
        if name.startswith(prefix):
            return family
    return f"unknown:{name.split(':')[0]}"


class ModelSpec(BaseModel):
    """Which provider and model serve one role."""

    provider: Provider = "ollama"
    model: str = "gemma4:12b"
    #: Whether a reasoning model deliberates before answering this role's calls.
    #: ``None`` leaves the backend's own default alone, which is what a model
    #: with no reasoning mode needs.
    #:
    #: It belongs in the config rather than in the provider because it changes
    #: what the model does, not merely how fast: every reply here is a small
    #: structured object chosen from a closed set, and deliberation is
    #: proportionally expensive. Recorded in the manifest, so a run states which
    #: it used.
    think: bool | None = None

    def label(self) -> str:
        thinking = "" if self.think is None else f" (think={str(self.think).lower()})"
        return f"{self.provider}/{self.model}{thinking}"


class TutorSpec(ModelSpec):
    #: ``template`` emits hints from the misconception catalogue at the level the
    #: scaffolding predicate asks for — no model involved.
    impl: TutorImpl = "llm"


class DiagnosticSpec(ModelSpec):
    #: ``oracle`` reads the simulator's injected label directly (perfect
    #: diagnosis); ``noised_oracle`` corrupts it at ``noise_rate``. Together with
    #: ``llm`` these are the three conditions compared to isolate how diagnostic
    #: error propagates into system-level outcomes.
    impl: DiagnosticImpl = "llm"
    noise_rate: float = Field(default=0.0, ge=0.0, le=1.0)

    @model_validator(mode="after")
    def _check_noise_rate(self) -> DiagnosticSpec:
        if self.impl == "noised_oracle" and self.noise_rate == 0.0:
            raise ValueError(
                "diagnostic.impl='noised_oracle' with noise_rate=0.0 is just an "
                "oracle; set noise_rate to the measured LLM error rate, or use "
                "impl='oracle'"
            )
        return self


class PlannerSpec(ModelSpec):
    #: ``goal_directed`` routes toward the declared goals from the learner
    #: model; ``greedy`` selects from the mastery frontier with no target;
    #: ``oracle`` may additionally see the simulator's true profile and is the
    #: upper bound the real planner's regret is measured against.
    impl: PlannerImpl = "llm"
    #: How the learner wants to reach the goal. A property of the learner, not
    #: of the architecture, so it must be **held identical across arms** in a
    #: paired comparison — it changes behaviour on its own, and varying it with
    #: the arm would confound the two.
    emphasis: Emphasis = Emphasis.CONSOLIDATE
    #: Consecutive correct answers before the decoupled planner moves on. Its
    #: view carries no per-concept estimate, so this stream is the only signal
    #: it has to advance on.
    advance_after: int = Field(default=2, ge=1)
    #: What the decoupled planner does when its walk reaches the end of the
    #: syllabus. ``stop`` ends the session; ``cycle`` starts the walk again.
    #:
    #: This is not a detail. Stopping is not forced by the missing learner model
    #: — a planner seeing only item correctness has no reason to give up rather
    #: than revise — and it makes the decoupled arm attempt fewer items than the
    #: coupled one, which confounds every outcome that grows with practice.
    #: ``cycle`` is the more charitable baseline and removes that difference.
    on_exhaustion: Literal["stop", "cycle"] = "stop"


class AgentsConfig(BaseModel):
    tutor: TutorSpec = Field(default_factory=lambda: TutorSpec())
    diagnostic: DiagnosticSpec = Field(default_factory=lambda: DiagnosticSpec())
    planner: PlannerSpec = Field(default_factory=lambda: PlannerSpec())


class SimulatorConfig(BaseModel):
    #: ``symbolic`` removes the LLM from the simulator entirely — the rule
    #: engine's decision is used verbatim. ``llm`` renders it as student prose.
    surface: SurfaceMode = "symbolic"
    surface_model: ModelSpec = Field(
        default_factory=lambda: ModelSpec(provider="ollama", model="gpt-oss:20b")
    )
    #: Misconceptions drawn per learner, and the initial firing probability range.
    misconceptions_per_learner: int = 2
    p_fire_range: tuple[float, float] = (0.6, 0.9)
    #: Multiplicative decay applied to a misconception's firing probability when
    #: a hint correctly targets it.
    remediation_factor: float = 0.55


class BKTConfig(BaseModel):
    """Bayesian Knowledge Tracing parameters (Corbett & Anderson, 1995)."""

    p_init: float = Field(default=0.15, ge=0.0, le=1.0)
    p_transit: float = Field(default=0.20, ge=0.0, le=1.0)
    p_guess: float = Field(default=0.20, ge=0.0, le=1.0)
    p_slip: float = Field(default=0.10, ge=0.0, le=1.0)

    @model_validator(mode="after")
    def _check_identifiability(self) -> BKTConfig:
        # Beck & Chang (2007): guess + slip >= 1 makes the model degenerate —
        # evidence updates run backwards.
        if self.p_guess + self.p_slip >= 1.0:
            raise ValueError(
                f"BKT is degenerate when p_guess + p_slip >= 1 "
                f"(got {self.p_guess} + {self.p_slip}); evidence would update backwards"
            )
        return self


class ZPDConfig(BaseModel):
    """Where the zone of proximal development is drawn.

    A concept is in the frontier when it is not yet independently mastered
    (``P(mastery) < theta_upper``) but every prerequisite is
    (``P(mastery) > theta_lower``).
    """

    theta_lower: float = Field(default=0.70, ge=0.0, le=1.0)
    theta_upper: float = Field(default=0.90, ge=0.0, le=1.0)

    @model_validator(mode="after")
    def _check_zpd_band(self) -> ZPDConfig:
        if self.theta_lower >= self.theta_upper:
            raise ValueError(
                f"ZPD band is empty: theta_lower ({self.theta_lower}) must be "
                f"< theta_upper ({self.theta_upper})"
            )
        return self


class ArbitrationConfig(BaseModel):
    """When real-time evidence may revise the plan."""

    #: Mastery-delta replanning threshold. Swept in sensitivity runs.
    theta: float = Field(default=0.15, gt=0.0, le=1.0)
    #: Repeats of one misconception within the rolling window that force a replan.
    k_repeats: int = Field(default=2, ge=1)
    #: Rate limit, to stop the planner thrashing between concepts.
    min_items_between_replans: int = Field(default=2, ge=0)
    #: Rolling error-trace length held in the learner state.
    error_trace_length: int = Field(default=20, ge=1)


class CohortConfig(BaseModel):
    n_learners: int = Field(default=3, ge=1)
    #: Practice items before the post-test, per learner.
    max_items: int = Field(default=20, ge=1)
    #: Max student steps allowed on one item before moving on.
    max_steps_per_item: int = Field(default=3, ge=1)


class PathsConfig(BaseModel):
    results_dir: Path = Path("results")
    cache_dir: Path = Path(".cache/llm")


class Config(BaseModel):
    """A complete, reproducible run specification."""

    run_name: str = "unnamed"
    domain: str = "toy_algebra"
    arm: Arm = "coupled"
    seed: int = 20260807

    cohort: CohortConfig = Field(default_factory=lambda: CohortConfig())
    simulator: SimulatorConfig = Field(default_factory=lambda: SimulatorConfig())
    agents: AgentsConfig = Field(default_factory=lambda: AgentsConfig())
    bkt: BKTConfig = Field(default_factory=lambda: BKTConfig())
    zpd: ZPDConfig = Field(default_factory=lambda: ZPDConfig())
    arbitration: ArbitrationConfig = Field(default_factory=lambda: ArbitrationConfig())
    paths: PathsConfig = Field(default_factory=lambda: PathsConfig())

    @model_validator(mode="after")
    def _check_simulator_family(self) -> Config:
        """Circularity control.

        The simulated learner must not be generated by the same model lineage
        that diagnoses it. Only bites when both sides actually call a model: in
        ``symbolic`` mode no LLM produces the student's step, and an oracle
        diagnostic reads the injected label rather than inferring it.
        """
        if self.simulator.surface != "llm" or self.agents.diagnostic.impl != "llm":
            return self
        sim = model_family(self.simulator.surface_model.model)
        diag = model_family(self.agents.diagnostic.model)
        if sim == diag:
            raise ValueError(
                f"Circularity control violated: the simulator surface model "
                f"({self.simulator.surface_model.model}) and the diagnostic agent "
                f"({self.agents.diagnostic.model}) are both from family '{sim}'. "
                f"The simulated learner must not be generated by the same model "
                f"lineage that diagnoses it. Pick a different family, or set "
                f"simulator.surface: symbolic."
            )
        return self

    def uses_llm(self) -> bool:
        """True when this run invokes any model at all.

        Runs where this is False are fast and exactly reproducible, which is
        what the end-to-end smoke run and the threshold sweep rely on.
        """
        return (
            self.simulator.surface == "llm"
            or self.agents.tutor.impl == "llm"
            or self.agents.diagnostic.impl == "llm"
            or self.agents.planner.impl == "llm"
        )

    def content_hash(self) -> str:
        """Stable hash of the config, for the run manifest."""
        payload = json.dumps(self.model_dump(mode="json"), sort_keys=True)
        return hashlib.sha256(payload.encode()).hexdigest()[:16]

    @classmethod
    def from_yaml(cls, path: str | Path) -> Config:
        path = Path(path)
        with path.open() as fh:
            data = yaml.safe_load(fh) or {}
        return cls.model_validate(data)
