"""Run configuration.

Configs are YAML files under ``experiments/configs/``. Everything the
orchestration loop, the agents and the evaluation harness need is declared here,
so a run is reproducible from ``(config file, seed, git SHA)`` alone.

Two validators enforce invariants that a careless config edit could otherwise
break silently:

* ``_check_simulator_family`` — the simulated learner's surface model must come
  from a different model family than the diagnostic agent, so the learner is not
  generated by the same lineage that classifies it.
* ``_check_zpd_band`` — the mastery band must be non-degenerate.
"""

from __future__ import annotations

import hashlib
import json
from pathlib import Path
from typing import Literal

import yaml
from pydantic import BaseModel, Field, model_validator

from agent_newton.core.state.schema import Emphasis

Provider = Literal["ollama", "anthropic", "openai"]
Arm = Literal["coupled", "decoupled"]
SurfaceMode = Literal["symbolic", "llm"]
#: Who answers. ``human`` puts a person in the same loop the cohorts run.
LearnerKind = Literal["simulated", "human"]

# Each agent has an LLM implementation and at least one model-free counterpart.
# The counterparts are not merely test doubles — they are experimental
# conditions: the `oracle` and `noised_oracle` diagnostics are what the real one
# is compared against to attribute system outcomes to diagnostic error, and the
# model-free set as a whole is what makes fast, exactly reproducible runs
# possible.
TutorImpl = Literal["llm", "template"]
#: Which scaffolding ladder is in force. ``banded`` is what every measured
#: result was produced under; see :class:`ScaffoldingConfig`.
ScaffoldingPolicy = Literal["banded", "banded_plus"]
DiagnosticImpl = Literal["llm", "oracle", "noised_oracle"]

#: Which misconceptions the diagnostic agent may choose between — the item's
#: own concept, or the whole catalogue. Recorded on the run manifest, because
#: an accuracy figure measured over one is not comparable to the other.
LabelSpace = Literal["concept", "catalogue"]
#: Which of a held-out bank is administered. ``full`` is every item in it;
#: ``route`` narrows a returning learner's banks to the concepts still on the
#: way to their next goal. See ``CohortConfig.pretest_scope``.
BankScope = Literal["full", "route"]
#: ``goal_directed`` routes toward the domain's declared goals from the learner
#: model. ``greedy`` is the undirected predecessor — frontier selection with no
#: target — kept as the baseline the directed planner is compared against.
#: ``reverse`` and ``shuffled`` are ordering probes: they cover the same
#: material as ``goal_directed`` but violate the prerequisite order, so a
#: comparison against them measures whether that order matters at all.
PlannerImpl = Literal[
    "llm", "goal_directed", "greedy", "oracle", "reverse", "shuffled"
]


# Model-name prefix -> developer. Used only by the circularity check: what
# matters is that the simulator and the diagnostic do not share a lineage.
_FAMILY_PREFIXES: tuple[tuple[str, str], ...] = (
    ("gemma", "google"),
    ("gemini", "google"),
    ("gpt-oss", "openai"),
    ("gpt-", "openai"),
    ("o1", "openai"),
    ("o3", "openai"),
    ("claude", "anthropic"),
    ("qwen", "alibaba"),
    ("llama", "meta"),
    ("mistral", "mistral"),
    ("mixtral", "mistral"),
    ("phi", "microsoft"),
    ("deepseek", "deepseek"),
)


def model_family(model: str) -> str:
    """Best-effort developer lineage for a model name.

    Unknown models return ``"unknown:<name>"`` rather than a shared bucket, so
    two unrecognised models never compare equal and accidentally trip the
    circularity check into passing.
    """
    name = model.strip().lower()
    for prefix, family in _FAMILY_PREFIXES:
        if name.startswith(prefix):
            return family
    return f"unknown:{name.split(':')[0]}"


class ModelSpec(BaseModel):
    """Which provider and model serve one role."""

    provider: Provider = "ollama"
    model: str = "gemma4:12b"
    #: Whether a reasoning model deliberates before answering this role's calls.
    #: ``None`` leaves the backend's own default alone, which is what a model
    #: with no reasoning mode needs.
    #:
    #: It belongs in the config rather than in the provider because it changes
    #: what the model does, not merely how fast: every reply here is a small
    #: structured object chosen from a closed set, and deliberation is
    #: proportionally expensive. Recorded in the manifest, so a run states which
    #: it used.
    think: bool | None = None

    def label(self) -> str:
        thinking = "" if self.think is None else f" (think={str(self.think).lower()})"
        return f"{self.provider}/{self.model}{thinking}"


class TutorSpec(ModelSpec):
    #: ``template`` emits hints from the misconception catalogue at the level the
    #: scaffolding predicate asks for — no model involved.
    impl: TutorImpl = "llm"


class DiagnosticSpec(ModelSpec):
    #: ``oracle`` reads the simulator's injected label directly (perfect
    #: diagnosis); ``noised_oracle`` corrupts it at ``noise_rate``. Together with
    #: ``llm`` these are the three conditions compared to isolate how diagnostic
    #: error propagates into system-level outcomes.
    impl: DiagnosticImpl = "llm"
    noise_rate: float = Field(default=0.0, ge=0.0, le=1.0)
    #: Which misconceptions the model may choose between.
    #:
    #: ``concept`` offers only those belonging to the item's own concept;
    #: ``catalogue`` offers all of them. The wide space lets the agent return a
    #: label from an unrelated concept — an incoherence a human session showed
    #: is frequent rather than rare, and which a learner sees in the panel.
    #: Narrowing also makes the task easier, so the two are not interchangeable
    #: as measurements: ``evaluate diagnostic`` reports both.
    label_space: LabelSpace = "concept"

    @model_validator(mode="after")
    def _check_noise_rate(self) -> DiagnosticSpec:
        if self.impl == "noised_oracle" and self.noise_rate == 0.0:
            raise ValueError(
                "diagnostic.impl='noised_oracle' with noise_rate=0.0 is just an "
                "oracle; set noise_rate to the measured LLM error rate, or use "
                "impl='oracle'"
            )
        return self


class PlannerSpec(ModelSpec):
    #: ``goal_directed`` routes toward the declared goals from the learner
    #: model; ``greedy`` selects from the mastery frontier with no target;
    #: ``oracle`` may additionally see the simulator's true profile and is the
    #: upper bound the real planner's regret is measured against.
    impl: PlannerImpl = "llm"
    #: How the learner wants to reach the goal. A property of the learner, not
    #: of the architecture, so it must be **held identical across arms** in a
    #: paired comparison — it changes behaviour on its own, and varying it with
    #: the arm would confound the two.
    emphasis: Emphasis = Emphasis.CONSOLIDATE
    #: Consecutive correct answers before the decoupled planner moves on. Its
    #: view carries no per-concept estimate, so this stream is the only signal
    #: it has to advance on.
    advance_after: int = Field(default=2, ge=1)
    #: What the decoupled planner does when its walk reaches the end of the
    #: syllabus. ``stop`` ends the session; ``cycle`` starts the walk again.
    #:
    #: This is not a detail. Stopping is not forced by the missing learner model
    #: — a planner seeing only item correctness has no reason to give up rather
    #: than revise — and it makes the decoupled arm attempt fewer items than the
    #: coupled one, which confounds every outcome that grows with practice.
    #: ``cycle`` is the more charitable baseline and removes that difference.
    on_exhaustion: Literal["stop", "cycle"] = "stop"


class AgentsConfig(BaseModel):
    tutor: TutorSpec = Field(default_factory=lambda: TutorSpec())
    diagnostic: DiagnosticSpec = Field(default_factory=lambda: DiagnosticSpec())
    planner: PlannerSpec = Field(default_factory=lambda: PlannerSpec())


class SimulatorConfig(BaseModel):
    #: ``human`` replaces the rule engine with a person. Recorded here so the
    #: run manifest states it and so the configuration can be checked: a human
    #: has no injected misconception label, which several roles depend on.
    learner: LearnerKind = "simulated"
    #: ``symbolic`` removes the LLM from the simulator entirely — the rule
    #: engine's decision is used verbatim. ``llm`` renders it as student prose.
    surface: SurfaceMode = "symbolic"
    surface_model: ModelSpec = Field(
        default_factory=lambda: ModelSpec(provider="ollama", model="gpt-oss:20b")
    )
    #: Misconceptions drawn per learner, and the initial firing probability range.
    misconceptions_per_learner: int = 2
    p_fire_range: tuple[float, float] = (0.6, 0.9)
    #: Multiplicative decay applied to a misconception's firing probability when
    #: a hint correctly targets it.
    remediation_factor: float = 0.55
    #: How much a correct hint depends on the learner's prerequisites being
    #: sound, in [0, 1]. **Zero is today**, and zero must reproduce every
    #: measured number exactly — there is a test on that and the paired cohort
    #: is re-run to confirm it.
    #:
    #: The generator has no notion of sequencing: a step is a function of the
    #: profile, the item's probes and a seeded roll, and a measurement found
    #: prerequisite order to make no difference at all to what a simulated
    #: learner learns (+0.0008, p = 1.0, matched on coverage). So the outcome
    #: the architecture is judged on is one nothing in the generator can move,
    #: and an architecture evaluated on sequencing was being credited for
    #: something the simulator could not reward.
    #:
    #: This is that dependence, made explicit and given a dial. At ``k`` a
    #: correct hint on a concept whose foundations are shaky takes less well:
    #: ``1 - (1 - remediation_factor) * (1 - k * (1 - solidity))``. At k = 1 and
    #: no solidity the hint does nothing at all; at solidity 1 it always lands
    #: in full, whatever k is.
    #:
    #: **Swept, never chosen.** A strength tuned until the coupled arm wins
    #: assumes the conclusion. Swept from zero it supports a far better claim —
    #: "the advantage appears above this much prerequisite dependence" — and the
    #: ordering probes are re-run at each point, because if arbitrary order
    #: still ties prerequisite order then the dial is moving something else.
    #:
    #: Grounded in the same literature the catalogue is: prerequisite knowledge
    #: is among the strongest predictors of what instruction achieves, which is
    #: the claim the ZPD band operationalises on the planning side and nothing
    #: represented on the learning side.
    prerequisite_dependence: float = Field(default=0.0, ge=0.0, le=1.0)


class BKTConfig(BaseModel):
    """Bayesian Knowledge Tracing parameters (Corbett & Anderson, 1995)."""

    p_init: float = Field(default=0.15, ge=0.0, le=1.0)
    p_transit: float = Field(default=0.20, ge=0.0, le=1.0)
    p_guess: float = Field(default=0.20, ge=0.0, le=1.0)
    p_slip: float = Field(default=0.10, ge=0.0, le=1.0)

    @model_validator(mode="after")
    def _check_identifiability(self) -> BKTConfig:
        # Beck & Chang (2007): guess + slip >= 1 makes the model degenerate —
        # evidence updates run backwards.
        if self.p_guess + self.p_slip >= 1.0:
            raise ValueError(
                f"BKT is degenerate when p_guess + p_slip >= 1 "
                f"(got {self.p_guess} + {self.p_slip}); evidence would update backwards"
            )
        return self


class ZPDConfig(BaseModel):
    """Where the zone of proximal development is drawn.

    A concept is in the frontier when it is not yet independently mastered
    (``P(mastery) < theta_upper``) but every prerequisite is
    (``P(mastery) > theta_lower``).
    """

    theta_lower: float = Field(default=0.70, ge=0.0, le=1.0)
    theta_upper: float = Field(default=0.90, ge=0.0, le=1.0)

    @model_validator(mode="after")
    def _check_zpd_band(self) -> ZPDConfig:
        # ⚠️ Posteriors are clamped away from 1.0 (`bkt._EPSILON`), so a
        # `theta_upper` of exactly 1.0 is an edge no estimate can ever cross:
        # every concept stays in the frontier forever, nothing is ever mastered,
        # and `goals_mastered` is zero for every learner in the run. It looks
        # like a legitimate setting and silently guarantees a null.
        if self.theta_upper >= 1.0:
            raise ValueError(
                f"theta_upper ({self.theta_upper}) must be below 1.0: posteriors "
                f"are clamped below 1.0, so mastery could never be reached and "
                f"no goal could ever be recorded as mastered"
            )
        if self.theta_lower >= self.theta_upper:
            raise ValueError(
                f"ZPD band is empty: theta_lower ({self.theta_lower}) must be "
                f"< theta_upper ({self.theta_upper})"
            )
        return self


class ScaffoldingConfig(BaseModel):
    """How much support a learner is given, and when.

    Two knobs, both defaulting to the behaviour every measured result was
    produced under, so a run that does not mention this block behaves exactly as
    it did before the block existed.
    """

    #: Which ladder the reactive hint level comes from.
    #:
    #: ``banded`` is the original rule: a nudge above ``theta_lower``, a targeted
    #: hint above ``theta_lower / 2``, a worked step below it, escalating on
    #: repeated failure to a ceiling of ``worked_step``.
    #:
    #: ``banded_plus`` reads every cut point off the band instead. Above
    #: ``theta_upper`` nothing is disclosed at all; inside the band escalation
    #: stops at ``targeted``, so a learner the model believes is nearly there is
    #: never handed the step; below ``theta_lower`` the original two levels
    #: remain. ``theta_lower / 2`` survives only as the boundary between naming
    #: the error and working the step, which is the one place it was ever doing
    #: work.
    policy: ScaffoldingPolicy = "banded"
    #: Whether support may be given *before* the first attempt.
    #:
    #: Off, everything support does is reactive: the tutor is called only after
    #: a step has already failed. On, a learner below ``theta_lower`` is shown
    #: the rule — and further down, a solved example on other numbers — beside
    #: the question itself.
    #:
    #: **Off for every cohort, and it must stay off.** Not because it would
    #: corrupt a measurement: the simulated learner improves only through
    #: ``receive_hint``, so nothing shown at presentation reaches it and no
    #: cohort number can move. It stays off because that inertness is a property
    #: of today's simulator rather than of the design, and a cohort quietly
    #: running with support on would stop being the run the numbers were
    #: produced under the moment that changed.
    offer_at_presentation: bool = False


class DecayConfig(BaseModel):
    """How the learner model goes stale between sessions.

    Off by default: ``half_life_days = None`` means no decay, so every
    single-session run behaves exactly as it did before this existed and the
    first study's numbers stay reproducible.

    Applies to the shared state, so it is **identical in both arms** — but only
    the coupled arm can see the result, because only its view carries the
    posteriors. That asymmetry is the manipulation, not a confound: a planner
    that cannot read mastery cannot notice that mastery has decayed.
    """

    #: Days for a posterior to close half the distance to the prior. None
    #: disables decay entirely.
    half_life_days: float | None = Field(default=None, gt=0.0)

    @property
    def enabled(self) -> bool:
        return self.half_life_days is not None


class ArbitrationConfig(BaseModel):
    """When real-time evidence may revise the plan."""

    #: Mastery-delta replanning threshold. Swept in sensitivity runs.
    theta: float = Field(default=0.15, gt=0.0, le=1.0)
    #: Repeats of one misconception within the rolling window that force a replan.
    k_repeats: int = Field(default=2, ge=1)
    #: Rate limit, to stop the planner thrashing between concepts.
    min_items_between_replans: int = Field(default=2, ge=0)
    #: Rolling error-trace length held in the learner state.
    error_trace_length: int = Field(default=20, ge=1)


class CohortConfig(BaseModel):
    n_learners: int = Field(default=3, ge=1)
    #: Practice items before the post-test, per learner.
    max_items: int = Field(default=20, ge=1)
    #: Max student steps allowed on one item before moving on.
    #:
    #: Steps the verifier could **read**. A response it could not parse is a
    #: failure to measure rather than an attempt at the exercise — it updates no
    #: estimate and enters no error trace — so charging one against this budget
    #: would spend the learner's attempts on the verifier's failure.
    #: ``max_unreadable_per_item`` bounds those separately.
    max_steps_per_item: int = Field(default=3, ge=1)
    #: Responses the verifier could not read before an item is given up on.
    #:
    #: Needed because ``max_steps_per_item`` no longer bounds them: without a
    #: cap of its own, someone pressing enter on an empty answer would be asked
    #: the same question forever. Total per item rather than consecutive, so a
    #: run broken up by a readable answer still terminates.
    #:
    #: Inert for every cohort. ``domain validate`` requires each buggy rule's
    #: output to verify as incorrect and each stated answer to verify as
    #: correct, so a simulated learner cannot produce an unreadable response at
    #: all — there is a test on that.
    max_unreadable_per_item: int = Field(default=3, ge=1)
    #: Whether to administer the held-out pre- and post-test banks.
    #:
    #: Always true for a cohort — they are what pre/post gain is measured from.
    #: A human sitting at a keyboard is a different case: the banks add thirty
    #: questions of pure measurement around a short session, and they update no
    #: state, so skipping them costs the demo nothing but the gain figure.
    administer_tests: bool = True
    #: Whether the pre-test's results seed the learner model before practice.
    #:
    #: **Off for every cohort, and it must stay off.** Seeding does not teach —
    #: no hints are given during a test — but it changes the *starting
    #: frontier*, and the coupled planner routes from the frontier while the
    #: decoupled one structurally cannot. Turning this on for an experiment
    #: therefore hands the coupled arm an advantage from the first item and
    #: inflates the effect being measured. On for the demo, where a person who
    #: has just sat a test reasonably expects it to count for something.
    seed_from_pretest: bool = False
    #: How many observations one pre-test answer is worth when seeding.
    #:
    #: At 1 a correct answer lifts a concept from the prior to about 0.44,
    #: well under ``theta_upper``, so a concept the learner has just
    #: demonstrated stays selectable and costs roughly two more items to
    #: re-prove. A human sitting measured the cost: 21 of 24 training steps went
    #: to concepts the pre-test already had right, and five real gaps were never
    #: reached inside the budget.
    #:
    #: Above 1 the answer is treated as that many independent observations, so
    #: it can clear the band and the concept is skipped. The justification is
    #: that a held-out answer is given unaided while a practice answer may
    #: follow a hint. The cost, stated because it is real: each concept has one
    #: pre-test item, so a lucky guess skips it for the whole sitting.
    #:
    #: Inert unless ``seed_from_pretest`` is on, and that is off for every
    #: cohort.
    pretest_weight: int = Field(default=1, ge=1)
    #: Floor a seeded estimate may not fall below. 0.0 is no floor.
    #:
    #: Exists because two correct things combined into a wrong one. Seeding at
    #: ``pretest_weight: 3`` drops a missed concept to about 0.0003, and
    #: ``hint_level`` returns ``WORKED_STEP`` for anything under
    #: ``theta_lower / 2``. So every concept the pre-test flagged as a gap
    #: received maximum support from its first attempt, for the whole sitting —
    #: the scaffolding ladder was dead on exactly the concepts being taught. A
    #: human sitting spent 41 steps that way and never saw a nudge or a targeted
    #: hint; the teaching record's ``not_attempted`` is what showed it.
    #:
    #: A floor keeps the concept a priority — still far below ``theta_upper``,
    #: so it stays selectable and still ranks first under ``consolidate`` — while
    #: leaving room for support to start lower and escalate.
    #:
    #: **It must stay below ``theta_lower``.** A prerequisite above that opens
    #: its dependants, so a floor at or above it would let a *wrong* pre-test
    #: answer unlock the material behind it. There is a check on that.
    seed_floor: float = Field(default=0.0, ge=0.0, lt=1.0)
    #: How much of the held-out banks a **returning** learner sits.
    #:
    #: ``full`` administers every item in the bank every sitting, which is what
    #: every measured result was produced under and what a cohort must keep: the
    #: banks are the instrument, and an instrument that changes between arms or
    #: between sittings measures nothing comparable.
    #:
    #: ``route`` narrows both banks to the concepts still on the way to the
    #: learner's next goal. It applies only to a resumed sitting — a first one
    #: has no history to narrow against and needs the baseline — and it exists
    #: because the alternatives are worse for a person. Administering the same
    #: fixed bank every sitting lets familiarity with it accumulate on exactly
    #: the items the outcome is read from, and administering it only once never
    #: re-measures what a gap has cost.
    #:
    #: Three consequences, all of which have to be honoured downstream:
    #:
    #: * **Both banks narrow to the same set**, fixed before the pre-test is
    #:   sat. Scoping them independently, or recomputing the route after
    #:   training, would compute a gain between two different instruments.
    #: * **``concepts_missed`` means less than it did**: gaps outside the route
    #:   are not measured, so they are not found. ``dose_on_gap`` divides by the
    #:   training that went to concepts the bank actually covered, so it stays a
    #:   share of what was measured rather than of everything.
    #: * A learner with no goal left to reach falls back to the full bank. There
    #:   is no route to narrow to, and a stale-estimate re-check across the whole
    #:   syllabus is what a returning learner needs at that point anyway.
    #:
    #: One case is worth knowing about rather than discovering: a learner who
    #: gets the whole re-check right has by that fact cleared the route it
    #: measured, and the sitting then trains what lies beyond it — which the
    #: banks did not ask about at either end. The gain is then a true statement
    #: about concepts that were already fine, and the training that happened is
    #: outside it. Marked in the sitting's own panel rather than folded into a
    #: figure that could not see it.
    pretest_scope: BankScope = "full"
    #: Times a concept may be worked before it stops being chosen.
    #:
    #: None is unlimited, which is what every run does today and what every
    #: measured result was produced under. Kept as a swept parameter including
    #: its own absence rather than switched on: a dwelling policy tuned until
    #: the coupled arm wins would assume the conclusion, while a swept one
    #: supports the far better claim that the advantage appears above a stated
    #: amount of persistence.
    #:
    #: The behaviour it changes: ``consolidate`` ranks by recent errors, so a
    #: concept a learner keeps failing attracts further selection. That is the
    #: intent — difficulty is where consolidation belongs — but it has no floor,
    #: and with the pre-test now skipping demonstrated concepts a stuck learner
    #: has fewer places to be moved along to. One verification run put all sixty
    #: of its steps on a single concept.
    #:
    #: Set, the concept is recorded as a weakness and ranked last, so it is
    #: chosen only when nothing else on the way to the goal is available.
    max_visits_per_concept: int | None = Field(default=None, ge=1)


class PathsConfig(BaseModel):
    results_dir: Path = Path("results")
    cache_dir: Path = Path(".cache/llm")
    #: Where learners persist between sittings. One file, so a sequence can be
    #: queried in one place — and so a human learner and a simulated one can be
    #: compared without joining across two stores.
    store_path: Path = Path("results/learners.db")


class Config(BaseModel):
    """A complete, reproducible run specification."""

    run_name: str = "unnamed"
    domain: str = "toy_algebra"
    arm: Arm = "coupled"
    seed: int = 20260807

    cohort: CohortConfig = Field(default_factory=lambda: CohortConfig())
    simulator: SimulatorConfig = Field(default_factory=lambda: SimulatorConfig())
    agents: AgentsConfig = Field(default_factory=lambda: AgentsConfig())
    bkt: BKTConfig = Field(default_factory=lambda: BKTConfig())
    zpd: ZPDConfig = Field(default_factory=lambda: ZPDConfig())
    scaffolding: ScaffoldingConfig = Field(
        default_factory=lambda: ScaffoldingConfig()
    )
    arbitration: ArbitrationConfig = Field(default_factory=lambda: ArbitrationConfig())
    decay: DecayConfig = Field(default_factory=lambda: DecayConfig())
    paths: PathsConfig = Field(default_factory=lambda: PathsConfig())

    @model_validator(mode="after")
    def _check_seed_floor(self) -> Config:
        """A seeded estimate may not reach the level that unlocks dependants.

        The frontier admits a concept when every prerequisite clears
        ``theta_lower``. A floor at or above it would mean a pre-test answer the
        learner got *wrong* opened the material behind it — the opposite of what
        seeding is for, and it would happen silently.
        """
        if self.cohort.seed_floor >= self.zpd.theta_lower:
            raise ValueError(
                f"cohort.seed_floor ({self.cohort.seed_floor}) must stay below "
                f"zpd.theta_lower ({self.zpd.theta_lower}): a seeded concept at "
                f"or above it would unlock its dependants, so a wrong pre-test "
                f"answer would open the material that depends on it"
            )
        return self

    @model_validator(mode="after")
    def _check_simulator_family(self) -> Config:
        """Circularity control.

        The simulated learner must not be generated by the same model lineage
        that diagnoses it. Only bites when both sides actually call a model: in
        ``symbolic`` mode no LLM produces the student's step, and an oracle
        diagnostic reads the injected label rather than inferring it.
        """
        if self.simulator.surface != "llm" or self.agents.diagnostic.impl != "llm":
            return self
        sim = model_family(self.simulator.surface_model.model)
        diag = model_family(self.agents.diagnostic.model)
        if sim == diag:
            raise ValueError(
                f"Circularity control violated: the simulator surface model "
                f"({self.simulator.surface_model.model}) and the diagnostic agent "
                f"({self.agents.diagnostic.model}) are both from family '{sim}'. "
                f"The simulated learner must not be generated by the same model "
                f"lineage that diagnoses it. Pick a different family, or set "
                f"simulator.surface: symbolic."
            )
        return self

    @model_validator(mode="after")
    def _check_human_diagnostic(self) -> Config:
        """A person has no injected label, so an oracle has nothing to read.

        Left unchecked, the session would run to completion and look fine: the
        oracle would name no misconception on every step, no hint would ever
        target anything, nothing would be remediated, and the run would report
        a diagnostic accuracy computed over an empty set. Every number would be
        the kind that looks plausible and means nothing.
        """
        if self.simulator.learner != "human":
            return self
        if self.agents.diagnostic.impl != "llm":
            raise ValueError(
                f"simulator.learner='human' needs agents.diagnostic.impl='llm'. "
                f"A person carries no injected misconception label, so "
                f"'{self.agents.diagnostic.impl}' would have nothing to read and "
                f"would diagnose nothing on every step — no hint would ever "
                f"target a misconception, and the session would look like it ran."
            )
        return self

    def uses_llm(self) -> bool:
        """True when this run invokes any model at all.

        Runs where this is False are fast and exactly reproducible, which is
        what the end-to-end smoke run and the threshold sweep rely on.
        """
        return (
            self.simulator.surface == "llm"
            or self.agents.tutor.impl == "llm"
            or self.agents.diagnostic.impl == "llm"
            or self.agents.planner.impl == "llm"
        )

    def content_hash(self) -> str:
        """Stable hash of the config, for the run manifest."""
        payload = json.dumps(self.model_dump(mode="json"), sort_keys=True)
        return hashlib.sha256(payload.encode()).hexdigest()[:16]

    @classmethod
    def from_yaml(cls, path: str | Path) -> Config:
        path = Path(path)
        with path.open() as fh:
            data = yaml.safe_load(fh) or {}
        return cls.model_validate(data)
